version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - '5672:5672' # Puerto para comunicación AMQP
      - '15672:15672' # Puerto para la interfaz de administración
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app_network

  ms-product:
    build:
      context: ./ms-product
    container_name: ms-product
    ports: 
      - "3001:3001"
    environment:
      PGHOST: postgres
      PGPORT: 5432
      PGUSER: admin
      PGPASSWORD: admin
      PGDATABASE: ms_product_db
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: admin
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - app_network

  mstrans-prod:
    build:
      context: ./mstrans-prod
    container_name: mstrans-prod
    ports: 
      - "3002:3002"
    environment:
      PGHOST: postgres
      PGPORT: 5432
      PGUSER: admin
      PGPASSWORD: admin
      PGDATABASE: mstrans_prod_db
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: admin
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - app_network

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  app_network:
